name: luzid_sdk

packages:
  - luzid-grpc
  - luzid-grpc-client
  - luzid-sdk

scripts:
  analyze:
    exec: dart analyze .
  outdated:
    exec: dart pub outdated
  upgrade:
    exec: dart pub upgrade --major-versions
