name: luzid_sdk
description: The Dart SDK to interact with luzid.app.
version: 1.0.0
repository: https://github.com/luzid-app/luzid-sdk

environment:
  sdk: ^3.2.6

dev_dependencies:
  melos: ^6.0.0
  lints: ^4.0.0
