name: luzid_grpc
description: The GRPC interface to the Luzid Validator service.
version: 0.0.2
repository: https://github.com/luzid-app/luzid-sdk

environment:
  sdk: ^3.2.6

dependencies:
  fixnum: ^1.1.0
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
