name: luzid_grpc_client
description: The GRPC client interface to the Luzid Validator service.
version: 0.0.4
repository: https://github.com/luzid-app/luzid-sdk

environment:
  sdk: ^3.2.6

dependencies:
  luzid_grpc: ^0.0.3
  grpc: ^3.2.4

dev_dependencies:
  lints: ^4.0.0
