#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

MODULE_ROOT="$DIR/.."
# NOTE: this expects luzid to be checked out next to this SDK repo
LUZID_REPO_ROOT="$MODULE_ROOT/../../../luzid"
LUZID_GRPC="$LUZID_REPO_ROOT/rs/luzid-grpc"
PROTO_DIR="$LUZID_GRPC/proto"
PROTO_OUT_DIR=$MODULE_ROOT/lib/proto

rm -rf $PROTO_OUT_DIR && mkdir -p $PROTO_OUT_DIR

mkdir -p $PROTO_OUT_DIR/{signals,requests}

protoc \
  --proto_path=$PROTO_DIR/types \
  --proto_path=$PROTO_DIR/signals \
  --proto_path=$PROTO_DIR/requests \
  --proto_path=$PROTO_DIR \
  --dart_out=grpc:$PROTO_OUT_DIR/signals \
  transaction_update.proto \
  validator_stats.proto \
  mutator_account_cloned.proto \
  validator_info.proto \
  snapshots_modified.proto \
  geyser_transaction_update.proto \
  validator_status.proto

protoc \
  --proto_path=$PROTO_DIR/types \
  --proto_path=$PROTO_DIR/signals \
  --proto_path=$PROTO_DIR/requests \
  --proto_path=$PROTO_DIR \
  --dart_out=grpc:$PROTO_OUT_DIR/requests \
  mutator_clone_account.proto \
  transaction.proto \
  app_ops.proto \
  snapshot_get_account.proto \
  validator_ops.proto \
  mutator_modify_account.proto \
  store_get_diffed_account_update.proto \
  snapshot_management.proto \
  store_get_account_data.proto \
  snapshot_restore.proto \
  rpc_get_account_info.proto \
  workspace.proto \
  rpc_request_airdrop.proto

protoc \
  --proto_path=$PROTO_DIR/types \
  --proto_path=$PROTO_DIR/signals \
  --proto_path=$PROTO_DIR/requests \
  --proto_path=$PROTO_DIR \
  --dart_out=grpc:$PROTO_OUT_DIR \
  _root.proto
