name: Build+Test+Lint

inputs:
  node-version:
    description: Version of Node.js to use
    required: true
  test:
    description: If set, tests will run via `yarn test`
    required: false
    default: true
  working-directory:
    description: Directory to run the action steps in
    required: true

runs:
  using: 'composite'

  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'
        cache-dependency-path: ${{ inputs.working-directory }}/yarn.lock

    - name: Install Dependencies
      run: yarn install
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    # Disabled until depcheck fixes the ESM issue present at v1.4.7
    # - name: Dependency check
    #   run: yarn depcheck
    #   shell: bash
    #   working-directory: ${{ inputs.working-directory }}

    - name: Build
      run: yarn build
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Test
      if: ${{ inputs.test == 'true' }}
      run: yarn test
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Lint
      run: yarn lint
      shell: bash
      working-directory: ${{ inputs.working-directory }}
