name: luzid_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/luzid-app/luzid-sdk

environment:
  sdk: ^3.2.6

dependencies:
  equatable: ^2.0.5
  fixnum: ^1.1.0
  luzid_grpc:
    path: ../luzid-grpc
  luzid_grpc_client:
    path: ../luzid-grpc-client

dev_dependencies:
  ansicolor: ^2.0.2
  lints: ^2.1.0
