name: luzid_sdk
description: Dart SDK for luzid.app.
version: 0.0.3
repository: https://github.com/luzid-app/luzid-sdk

environment:
  sdk: ^3.2.6

dependencies:
  equatable: ^2.0.5
  fixnum: ^1.1.0
  luzid_grpc: ^0.0.2
  luzid_grpc_client: ^0.0.3

dev_dependencies:
  ansicolor: ^2.0.2
  lints: ^4.0.0
