name: 'Luzid: Release MacOS'
on:
  push:
    tags:
      - "macos-v*.*.*"

jobs:
  release-macos-m1:
    runs-on: macos-14
    timeout-minutes: 90
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Luzid
        uses: actions/checkout@v4
        with:
          repository: luzid-app/luzid
          path: luzid
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Checkout Solana and Install Deps
        uses: ./luzid/.github/actions/checkout-solana-and-install-deps
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-personal-access-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'build-release-macos-cache-bust-000'
          workspaces: |
            luzid/rs -> target
          cache-targets: true
          cache-all-crates: true
          cache-on-failure: true

      ## Rust Backend
      - name: Add x86_64 Rust Target
        run: rustup target add x86_64-apple-darwin
        shell: bash

      ### X86_64 Build
      - name: Cargo Build X86_64
        run: make ci-build-macos-x86_64-release
        working-directory: luzid
        shell: bash

      - name: Show Rust Backend X86_64 Asset
        run: ls -la rs/target/x86_64-apple-darwin/release
        working-directory: luzid
        shell: bash

      - name: Move Rust Backend X86_64 Asset to Luzid Root
        run: mv rs/target/x86_64-apple-darwin/release/luzid luzid
        working-directory: luzid
        shell: bash

      - name: Packup Rust Backend X86_64 Asset
        run: |
          tar czvf luzid_x86_64-apple-darwin.tar.gz luzid
        working-directory: luzid
        shell: bash

      - name: Remove x86_64 Assets
        run: rm -f luzid
        working-directory: luzid
        shell: bash

      ### Arm Build
      - name: Cargo Build Arm
        run: make ci-build-macos-arm-release
        working-directory: luzid
        shell: bash

      - name: Show Rust Backend Arm Asset
        run: ls -la rs/target/release
        working-directory: luzid
        shell: bash

      - name: Move Rust Backend Arm Asset to Luzid Root
        run: mv rs/target/release/luzid luzid
        working-directory: luzid
        shell: bash

      - name: Packup Rust Backend Arm Asset
        run: |
          tar czvf luzid_aarch64-apple-darwin.tar.gz luzid
        working-directory: luzid
        shell: bash

      ## Flutter UI
      - name: Flutter create Macos (to get xcodeproj)
        run: flutter create --platforms=macos .
        working-directory: luzid/ui
        shell: bash

      - name: Flutter Build
        run: make ci-flutter-build-macos-release
        working-directory: luzid
        shell: bash

      ### Prepare Flutter Assets
      - name: Show Flutter Assets
        run: ls -la ui/build/macos/Build
        working-directory: luzid

      - name: Move Flutter Assets to Luzid Root
        run: mv ui/build/macos/Build/Products/Release/luzid.app LuzidUI.app
        working-directory: luzid
        shell: bash

      - name: Packup Flutter Assets
        run: |
          tar czvf LuzidUI.app.tar.gz LuzidUI.app
        working-directory: luzid
        shell: bash

      - name: Show Release x86_64 Asset
        run: ls -la luzid/luzid_x86_64-apple-darwin.tar.gz
        shell: bash

      - name: Show Release Arm Asset
        run: ls -la luzid/luzid_aarch64-apple-darwin.tar.gz
        shell: bash

      - name: Show Release Flutter UI Asset
        run: ls -la luzid/LuzidUI.app.tar.gz
        shell: bash

      ## Publish Release
      - name: Resolve version
        id: vars
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            luzid/luzid_x86_64-apple-darwin.tar.gz
            luzid/luzid_aarch64-apple-darwin.tar.gz
            luzid/LuzidUI.app.tar.gz
          body: ${{ github.event.head_commit.message }}
          draft: true
          tag_name: ${{ env.TAG_NAME }}
