name: 'Luzid: Release MacOS'
on:
  push:
    tags:
      - "macos-v*.*.*"

jobs:
  release-macos-m1:
    runs-on: macos-14
    timeout-minutes: 90
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Luzid
        uses: actions/checkout@v4
        with:
          repository: luzid-app/luzid
          path: luzid
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Checkout Solana and Install Deps
        uses: ./luzid/.github/actions/checkout-solana-and-install-deps
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gh-personal-access-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: 'build-release-macos-m1'
          workspaces: |
            luzid -> build/macos/Build/Intermediates.noindex/Pods.build/Release/rinf.build
          cache-targets: true
          cache-all-crates: true
          cache-on-failure: true

      - name: Flutter create Macos (to get xcodeproj)
        run: flutter create --platforms=macos .
        working-directory: luzid
        shell: bash

      - name: Rinf Message Generation
        run: dart run rinf message
        working-directory: luzid
        shell: bash

      - name: Flutter Build
        run: make ci-flutter-build-macos-release
        working-directory: luzid
        shell: bash
        env:
          RINF: 1

      ## Prepare Flutter Assets
      - name: Show Flutter Assets
        run: ls -la build/macos/Build
        working-directory: luzid

      - name: Move Flutter Assets to Luzid Root
        run: mv build/macos/Build/Products/Release/luzid.app Luzid.app
        working-directory: luzid
        shell: bash

      - name: Packup Flutter Assets
        run: |
          tar czvf luzid.app.tar.gz Luzid.app
        working-directory: luzid
        shell: bash


      ## Build and Prepare Headless Assets
      - name: Add x86_64 Rust Target
        run: rustup target add x86_64-apple-darwin
        shell: bash

      ## X86_64 Build
      - name: Cargo Build X86_64
        run: make ci-build-macos-x86_64-release
        working-directory: luzid
        shell: bash
        env:
          RINF: 1

      - name: Show Headless X86_64 Asset
        run: ls -la target/x86_64-apple-darwin/release
        working-directory: luzid
        shell: bash

      - name: Move Headless X86_64 Asset to Luzid Root
        run: mv target/x86_64-apple-darwin/release/luzid_server lzd
        working-directory: luzid
        shell: bash

      - name: Packup Headless X86_64 Asset
        run: |
          tar czvf luzid_x86_64-apple-darwin.tar.gz lzd
        working-directory: luzid
        shell: bash

      - name: Remove x86_64 Assets
        run: rm -rf lzd
        working-directory: luzid
        shell: bash

      ## Arm Build
      - name: Cargo Build Arm
        run: make ci-build-macos-arm-release
        working-directory: luzid
        shell: bash
        env:
          RINF: 1

      - name: Show Headless Arm Asset
        run: ls -la target/release
        working-directory: luzid
        shell: bash

      - name: Move Headless Arm Asset to Luzid Root
        run: mv target/release/luzid_server lzd
        working-directory: luzid
        shell: bash

      - name: Packup Headless Arm Asset
        run: |
          tar czvf luzid_aarch64-apple-darwin.tar.gz lzd
        working-directory: luzid
        shell: bash

      ## Publish Release
      - name: Resolve version
        id: vars
        run: |
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            luzid/lzd_x86_64-apple-darwin.tar.gz
            luzid/lzd_aarch64-apple-darwin.tar.gz
            luzid/luzid.app.tar.gz
          body: ${{ github.event.head_commit.message }}
          draft: true
          tag_name: ${{ env.TAG_NAME }}
