name: 'Luzid: Release Windows'
on:
  push:
    branches:
      - ci/windows-release
    tags:
      - "windows-v*.*.*"

jobs:
  release-windows:
    runs-on: windows-latest
    timeout-minutes: 200
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Luzid
        uses: actions/checkout@v4
        with:
          repository: luzid-app/luzid
          path: luzid
          ref: ci/windows
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter --version
      - run: dart --version

      - name: Install Luzid Flutter Dependencies
        run: flutter pub get
        working-directory: luzid/ui

      - name: Flutter Build
        run: make ci-flutter-build-windows-release
        working-directory: luzid

      ## Prepare Flutter Assets
      - name: Show Flutter Assets
        run: dir ui\build
        working-directory: luzid

      - name: Show Flutter Assets
        run: dir ui\build\windows\x64\runner\Release\
        working-directory: luzid

          # - name: Move Flutter Assets to Luzid Root
          #   run: mv ui/build/linux/x64/release/bundle luzidui
          #   working-directory: luzid
          #   shell: bash

          # - name: Packup Flutter Assets
          #   run: |
          #     tar czvf luzidui.tar.gz luzidui
          #   working-directory: luzid
          #   shell: bash

          # - name: Show Release Flutter UI Asset
          #   run: ls -la luzid/luzidui.tar.gz
          #   shell: bash

      ## Publish Release
      #- name: Resolve version
      #  id: vars
      #  run: |
      #    echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      #- name: Release Assets
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    files: |
      #      luzid/luzid.tar.gz
      #      luzid/luzidui.tar.gz
      #    body: ${{ github.event.head_commit.message }}

      #    draft: true
      #    tag_name: ${{ env.TAG_NAME }}
